### ISSUE TITLE
Feature Request: Create todo from interstitial journal

### ISSUE THREAD

**Issue by m42e** [kookma/TW-Todolist#11]
Would be great to have the possibility to create a todo in a interstitial journal by adding a tag like `[]` or something to the text of the journal entry.

**Comment by kookma** [comment]
Hi @m42e 
I am afraid I did not understand your OP. Would you please explain in little more. What feature exactly you like?

**Comment by m42e** [comment]
Sure I can @kookma

Given the following Journal:
<img width="781" alt="Bildschirmfoto 2022-02-07 um 08 03 09" src="https://user-images.githubusercontent.com/2410802/152740389-e43a2793-f7c3-4178-a118-44d37a410cc8.png">

I'd like to have the last Point also as a todo item, so I can check it afterwards.
And It would be great to be able to do this with a tag in the journal entry.

And have something like that:
<img width="809" alt="Bildschirmfoto 2022-02-07 um 08 06 28" src="https://user-images.githubusercontent.com/2410802/152740822-499d5960-f91b-436e-ae6e-ca43d38064ef.png">

And have it in the todo list

<img width="791" alt="Bildschirmfoto 2022-02-07 um 08 07 07" src="https://user-images.githubusercontent.com/2410802/152740873-ad336322-ff5b-4203-b25c-59e543054c84.png">

Hope this make the intention more clear.

**Comment by kookma** [comment]
I got it!
Have you seen [Mehregan](https://github.com/kookma/TWE-Mehregan)?
It uses the Thinkup plugin which allow you have both of them!

**Comment by m42e** [comment]
Oh no, I didn't. Thanks for the hint I will have a look.

**Comment by kookma** [comment]
By the way what you need is not difficult and you may add this

It can use a macro like

```
<<todo>> description
```

These are like other categories: See https://kookma.github.io/TW-Todolist/#demo%2Fhowto

**Comment by m42e** [comment]
Ok, Mehregan works for me, as the small todolist at the bottom fits my needs.
