### ISSUE TITLE
Interstitial populating new journal entries, even though I removed it from Control Panel settings!

### ISSUE THREAD

**Issue by dixonge** [kookma/TW-Todolist#14]
Under Control Panel > Info > Text for New Journal Tiddlers I entered the Interstitial-ui macro code. On the next day it carried over all prior entries and added a second interstitial field. So I removed the macro code from the Control Panel, but now each day I still get prior interstitial journal entries show up in each new journal tiddler.

Very confusing!

**Comment by dixonge** [comment]
New journal entries are now populating with an empty Interstitial UI macro. Previous entries are not carrying over. I am not sure why. Also, I do not understand why the Interstitial UI is there at all as I removed it completely from the Control Panel settings. However, since it is working, I am closing this issue.

**Comment by kookma** [comment]
> Very confusing!

Why not using viewtemplate here?
By the way this is a TW issue
