### ISSUE TITLE
Interstitial Journal option to include date with the timestamp

### ISSUE THREAD

**Issue by barrelman70** [kookma/TW-Todolist#19]
First, big thanks for all the plugins you have worked on, they are awesome!!!

Is there or could there be an option to have the date included with the timestamp.  Maybe something like Jul 13 14:00?  I'm using this to keep track of key events and notes of projects that can span more than one day.  Currently I just put in an entry with the new date to separate what happened on what day, but it would be awesome if there was an option to just include the date with the timestamp.

**Comment by kookma** [comment]
Open $:/plugins/kookma/todolist/macros/interstitial-utility
look at `disp-journals-in-view-mod` macro and the date template. You can change it as you like.

My recommendation is: use interstitial journaling inside a journal tiddler, the title has date so do not use redundant info here.

**Comment by kookma** [comment]
Note that if you like the same format in edit mode you need to modify the format in edit macro beneath that view macro mentioned above.

**Comment by barrelman70** [comment]
That was just what I was looking for, thanks!
