### ISSUE TITLE
Lists steal cursor focus when writing elsewhere

### ISSUE THREAD

**Issue by ZeroKobold** [kookma/TW-Todolist#20]
When a Tiddler with a To Do List is open, the text cursor will jump to it when writing in another location.

Step to reproduce:
1. Create a To Do List using the plugin
2. Save the tiddler and leave it open
3. Create a new Tiddler and start typing

**Comment by kookma** [comment]
That's right! The reason is the focus has been set to yes in

https://github.com/kookma/TW-Todolist/blob/master/source/todolist/macros/task/add.tid

You can turn it off. 

You can use Kara plugin where it has option to explicitly set this to no!

**Comment by ZeroKobold** [comment]
I was able to disable that feature.
Thank you!
