### ISSUE TITLE
Issue setting todolist caption parameter

### ISSUE THREAD

**Issue by dhjackal** [kookma/TW-Todolist#23]
Hi Mohammad, 

I'm still testing the todolist plugin. It is very good btw. I will be using ALL the features now that I have spent some proper time learning them. 

A bug in the caption parameter setting.....while trying to type a long caption name directly into the macro call in edit mode the cursor jumps from the caption into the first line of the to do list in the preview pane.....so for instance tiddler looks like this

caption:"Tes" width:"" base:"">>

ting 

The latter characters get cut off and appear in the actual to do list. I'm not sure what (if anything) can be done about it but I thought I'd let you know. 

Declan

**Comment by kookma** [comment]
This is not a Todolist issue, but a TW issue. TW refreshes the preview window.
Close it and it will work as expected. 
The doc explains this.

**Comment by dhjackal** [comment]
Ah I see. Thanks Mohammad. I did think it was TW. Didn't know enough to try to pick it apart. I thought i'd read the doco fully and i saw this update ;

Release 1.4.2

    Apr 3rd, 2023
    [FIXED] A bug in displaying caption (in todolist-ui and interstitial-ui)

And thought this was the issue and the resolution. Have I missed something in the readme?
