### ISSUE TITLE
Feature request: Multiline todos

### ISSUE THREAD

**Issue by juanitocalero** [kookma/TW-Todolist#5]
It would be great if todos could (only sometimes) have more than one line, just for when you need to have some extra info in the todo, but you don't want to point to a new tiddler.

The carriage return could be triggered with Shift + Insert, is kind of a standard now.

Great great plugin, really useful!!

**Comment by kookma** [comment]
@juanitocalero  This is Tiny ToDO list and uses for single line. But there is a multi line with due date, and any custom fields called Task Manager in Shiraz plugin. have a look at https://kookma.github.io/TW-Shiraz/#demo%2Fdynamic-table%2Ftask-manager
