### ISSUE TITLE
feature request: Show all existing todolists

### ISSUE THREAD

**Issue by arteteco** [kookma/TW-Todolist#7]
Hello everyone,
I have many todos in my wiki, would be awesome to display them all in a tiddler, to have everything under control

Thanks!

**Comment by kookma** [comment]
@arteteco 
You can do this in many way!

1. Transclude those tiddlers in one for example if those tiddlers with todos are tagged with `myTag`
In a new tiddler put this snippet

<$list filter="[tag[myTag]"><$transclude mode=block/></$list>

2. If you now the base then use something like this. Here I assume my base is base1, base2, ...

```
<$list filter="base1 base2 base3" variable=prj>
<$macrocall $name=todolist-ui base=<<prj>> caption="""<h2 style="color:darkred;font-weight:lighter;"><<prj>></h2>""" />
</$list>
```

3. See https://kookma.github.io/TW-Todolist/#Multiple%20Todo%20List and how it create multiple todolists
