### ISSUE TITLE
Formatting issues with Categories

### ISSUE THREAD

**Issue by jiyosub** [kookma/TW-Todolist#8]
This may be my setup but I have three issues:

- I can't get categories to format.  
- When I hover above a todo item, it's not highlighted correctly
- ToDoList doesn't show up under settings

I have no doubt it's my fault for being so new at TW, but I love this plugin and really want it to work with my setup.  Any debugging help would be appreciated.  Everything else works beautifully.  

![screenshot_92](https://user-images.githubusercontent.com/1575077/135374079-21ce4a06-f255-4cac-affb-70305ab005a4.png)

![screenshot_93](https://user-images.githubusercontent.com/1575077/135374112-965253b3-82db-44d6-96a1-dd9f971cad86.png)

![screenshot_95](https://user-images.githubusercontent.com/1575077/135374053-8ba462ad-88c5-4fd8-b211-e05039b5e5c6.png)

**Comment by kookma** [comment]
@jiyosub - thank you for your feedback



> This may be my setup but I have three issues:
> 
> * I can't get categories to format.
Please check with a light palette. Use Vanilla palette and see if it works

> * When I hover above a todo item, it's not highlighted correctly
Please check with a light palette. Use Vanilla palette and see if it works

> * ToDoList doesn't show up under settings
Unfortunately Setting tab only work, if you have installed the official plugin CodeMirror. By the way you can access settings from sidebar/More/Todolist tab!

**Comment by jiyosub** [comment]
So. Switching between pallets worked. Swapping into vanilla and then back to solarized dark works. All the formatting is fine now. 

Also installing CodeMirror fixed the settings.  

Thanks for the reply. It's working great now. I integrated it with my kanban with no problems.

**Comment by jiyosub** [comment]
![image](https://user-images.githubusercontent.com/1575077/135460071-253138b1-8d29-4664-953b-4d4015b37d9f.png)

![image](https://user-images.githubusercontent.com/1575077/135460120-8bdfb71c-de8f-4dad-b9af-d61458c43c64.jpeg)

**Comment by jiyosub** [comment]
Now my last task is I want to make random todos all through my notes but somehow aggregate them all together under one caption in the sidebar.  I'd like to have all of those todos in one place with backlinks to the note I tagged. 

So for example in my journal note I might create a task to go for a run. In another note a task to read something. Then have both tasks show up in the side bar with links going back to the notes.

**Comment by kookma** [comment]
The simple solution to have all those ui again in sidebar! like

Shopping

Projects


Readings


Note that if you can todos-ui with the same state tiddler you can have it in multiple place! but merging tasks need some coding!

I may also recommend to have a look at Projectify and Kanban

**Comment by jiyosub** [comment]
Thanks again!
